spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://43.200.95.124:3306/studywithmeProject?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        format_sql: true
  jwt:
    secret: 

  redis:
    host: localhost
    port: 6379
