spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/zerobaseProject?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: Jesuslove1!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      properties:
        format_sql: true
  jwt:
    secret: rkskekfkakqktkdkwkckzkxkvkgkaaaaabbbb

  redis:
    host: localhost
    port: 6379